<a href="https://colab.research.google.com/github/arshi246/Pandas/blob/main/Pandas_Concept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Arshi

Roll_no : 874718

**Pandas**
# Pandas DataFrame Core Operations

Pandas is a Python library used for **working with structured and tabular data**.

It is very useful in:

- Data Science
- Machine Learning
- Data Analysis
- Artificial Intelligence
- Data Cleaning

The main data structure of Pandas is called a **DataFrame**.

A DataFrame stores data in the form of:
```
Rows + Columns
```

For example:

```
      Name    Age    Marks
0     Ali     20      80
1     Sara    21      90
2     Ahmed   19      75
```

We can imagine a DataFrame like an **Excel table**.

# 1. Import Pandas

First, we need to import Pandas.

`pd` is just a short name for Pandas.

After importing it, we can use Pandas functions like:

```python
pd.DataFrame()
pd.read_csv()
pd.concat()
pd.merge()
```

In [3]:
import pandas as pd

# 2. Creating a DataFrame

A DataFrame stores data in **rows and columns**.

We can create a DataFrame using a Python dictionary.

Here:

```
Name, Age, Marks → Columns

Ali, Sara, Ahmed → Data

0, 1, 2 → Index
```

A DataFrame is basically a **table inside Python**.

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 21, 19],
    "Marks": [80, 90, 75]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    Ali   20     80
1   Sara   21     90
2  Ahmed   19     75

# 3. Reading a Dataset

Most of the time, we do not manually create large DataFrames.

We load data from files.

For example, suppose we have:
```
students.csv
```

We can read it using:

```python
df = pd.read_csv("students.csv")

print(df)
```

To read an Excel file:

```python
df = pd.read_excel("students.xlsx")
```
The data from the file will be converted into a Pandas DataFrame.

The pattern is:

```
CSV / Excel File
       ↓
     Pandas
       ↓
   DataFrame
```

In [ ]:
df = pd.read_csv("/content/Social_media_impact_on_life.csv")
print(df)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat
1     STU_2024001   19  Female  Undergraduate        Instagram
2     STU_2024002   17  Female    High School           TikTok
3     STU_2024003   16  Female    High School          YouTube
4     STU_2024004   17    Male    High School         LinkedIn
...           ...  ...     ...            ...              ...
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
1                   4.6                  1.3  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
4                   3.3                  2.6  Smartphone
...                 ...                  ...         ...
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
1                      7.9                    3              True
2                      5.2                    1              True
3                      7.6                    4              True
4                      7.6                    4              True
...                    ...                  ...               ...
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
1                      Sometimes                    17.0                   90
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
4                          Never                    16.0                   84
...                          ...                     ...                  ...
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
1                         3.21     Beneficial
2                         3.00        Neutral
3                         3.42     Beneficial
4                         3.41     Beneficial
...                        ...            ...
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

[4500 rows x 16 columns]

# 4. Viewing Data

Large datasets can contain thousands of rows.

We normally do not print the complete dataset.

## head()

`head()` displays the first 5 rows.

In [ ]:
print(df.head())

    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok
3  STU_2024003   16  Female    High School          YouTube
4  STU_2024004   17    Male    High School         LinkedIn

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2
3                6.0                  2.3      Tablet                   7.6
4                3.3                  2.6  Smartphone                   7.6

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently
3                    4              True                   Sometimes
4                    4              True                       Never

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00
3                    15.0                   82                      3.42
4                    16.0                   84                      3.41

  Overall_Impact
0        Neutral
1     Beneficial
2        Neutral
3     Beneficial
4     Beneficial

To display the first 3 rows:

In [ ]:
print(df.head(3))

    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00

  Overall_Impact
0        Neutral
1     Beneficial
2        Neutral

## tail()

`tail()` displays the last 5 rows.

In [ ]:
print(df.tail())

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

To display the last 2 rows:

In [ ]:
print(df.tail(3))

       Student_ID  Age Gender Academic_Level Primary_Platform  \
4497  STU_2028497   19   Male  Undergraduate        Instagram
4498  STU_2028498   16   Male    High School         LinkedIn
4499  STU_2028499   24   Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

So:

```
head() → First rows

tail() → Last rows
```

# 5. Shape and Basic Properties

Suppose:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 21, 19],
    "Marks": [80, 90,75 ]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    Ali   20     80
1   Sara   21     90
2  Ahmed   19     75

## shape

`shape` tells us the number of rows and columns.

This means:

```
3 rows
3 columns
```

In [ ]:
print(f"Shape : {df.shape}")

Shape : (3, 3)

## columns

`columns` tells us the column names.

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='object')

## dtypes

`dtypes` tells us the data type of each column.

In [ ]:
print(df.dtypes)

Name     object
Age       int64
Marks     int64
dtype: object

# 6. DataFrame Information

`info()` gives us important information about the DataFrame.

info() is very useful when we start working with a new dataset.

It tells us:

```
Number of rows
Number of columns
Column names
Data types
Missing values
Memory usage
```

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

# 7. Statistical Summary

`describe()` gives us a statistical summary of numerical columns.

It can show:

```
count
mean
standard deviation
minimum
25%
50%
75%
maximum
```

For example, if we have student marks, describe() helps us quickly understand how the marks are distributed.

In [ ]:
print(df.describe())

        Age      Marks
count   3.0   3.000000
mean   20.0  81.666667
std     1.0   7.637626
min    19.0  75.000000
25%    19.5  77.500000
50%    20.0  80.000000
75%    20.5  85.000000
max    21.0  90.000000

# 8. Selecting Columns

Suppose:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 21, 19],
    "Marks": [80, 90, 75]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    Ali   20     80
1   Sara   21     90
2  Ahmed   19     75

To select only the Name column:

In [ ]:
print(df["Name"])

0      Ali
1     Sara
2    Ahmed
Name: Name, dtype: object

To select only Marks:

In [ ]:
print(df["Marks"])

0    80
1    90
2    75
Name: Marks, dtype: int64

## Selecting Multiple Columns

To select Name and Marks:

In [ ]:
print(df[["Name","Marks"]])

    Name  Marks
0    Ali     80
1   Sara     90
2  Ahmed     75

Important:

One column:

```python
df["Name"]
```

Multiple columns:

```python
df[["Name", "Marks"]]
```

# 9. Selecting Rows — loc and iloc

Pandas provides `loc` and `iloc` for selecting rows.

## loc

`loc` selects data using **index labels**.

In [ ]:
print(df.loc[0])

Name     Ali
Age       20
Marks     80
Name: 0, dtype: object

In [ ]:
print(df.loc[1])

Name     Sara
Age        21
Marks      90
Name: 1, dtype: object

In [ ]:
print(df.loc[2])

Name     Ahmed
Age         19
Marks       75
Name: 2, dtype: object

To get a specific value:

In [ ]:
print(df.loc[0,"Marks"])

80

## iloc

`iloc` selects data using **positions**.

In [ ]:
print(df.iloc[0])

Name     Ali
Age       20
Marks     80
Name: 0, dtype: object

To get the first row and second column:

In [ ]:
print(df.iloc[0,1])

20

The pattern is:

```
iloc[row_position, column_position]
```

Important difference:

```
loc  → Labels / Names

iloc → Integer Positions
```

# 10. Filtering Data

Filtering is one of the most important operations in data analysis.

Filtering means getting only the rows that match a condition.

Suppose:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "Marks": [45, 90, 75, 40]
}

df = pd.DataFrame(data)
df

     Name  Marks
0     Ali     45
1    Sara     90
2   Ahmed     75
3  Ayesha     40

To get students with marks greater than or equal to `50`:

In [ ]:
passed = df[df['Marks'] >=50 ]
print(passed)

    Name  Marks
1   Sara     90
2  Ahmed     75

isko aise read karo:

"Original df mein se woh rows do jahan df ke Marks 50 ya usse zyada hain."

To get failed students

In [ ]:
failed = df[df['Marks'] <50]
print(failed)

     Name  Marks
0     Ali     45
3  Ayesha     40

# 11. Adding a New Column

We can add a new column to an existing DataFrame.

Example:

In [ ]:
df["City"] = ["Karachi", "Lahore", "Karachi", "Islamabad"]
print(df)

     Name  Marks       City
0     Ali     45    Karachi
1    Sara     90     Lahore
2   Ahmed     75    Karachi
3  Ayesha     40  Islamabad

We can also create a column using calculations.

Example:

In [ ]:
df['Bonus Marks'] = df['Marks'] + 5
print(df)

     Name  Marks       City  Bonus Marks
0     Ali     45    Karachi           50
1    Sara     90     Lahore           95
2   Ahmed     75    Karachi           80
3  Ayesha     40  Islamabad           45

Pandas performs the operation on the complete column automatically.

# 12. Updating Values

We can change existing values inside a DataFrame.

Suppose Ali's marks are `45`.

We want to change them to `55`.

In [ ]:
df.loc[0,'Marks'] = 55
print(df)

     Name  Marks       City  Bonus Marks
0     Ali     55    Karachi           50
1    Sara     90     Lahore           95
2   Ahmed     75    Karachi           80
3  Ayesha     40  Islamabad           45

In [ ]:
df.iloc[0,1] = 60
df

     Name  Marks       City  Bonus Marks
0     Ali     60    Karachi           50
1    Sara     90     Lahore           95
2   Ahmed     75    Karachi           80
3  Ayesha     40  Islamabad           45

We can also update an entire column.

This adds 5 to every student's marks.

In [ ]:
df['Marks'] = df['Marks'] + 5
df

     Name  Marks       City  Bonus Marks
0     Ali     65    Karachi           50
1    Sara     95     Lahore           95
2   Ahmed     80    Karachi           80
3  Ayesha     45  Islamabad           45

# 13. Deleting Rows and Columns

Pandas uses `drop()` to remove data.

## Delete a Column

Here:

```
axis = 1
```

means we are deleting a **column**.


Remember:

```
axis = 0 → Rows

axis = 1 → Columns
```

In [ ]:
df = df.drop("Age",axis = 1)
df

,Student_ID,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

Delete a Row

In [ ]:
df = df.drop(0, axis=0, errors='ignore')
df

,Student_ID,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
1,STU_2024001,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
5,STU_2024005,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
print(df.index)

RangeIndex(start=1, stop=4500, step=1)

# 14. Handling Missing Values

Real datasets often contain missing data.

NaN means a value is missing.

Example:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [80, None, 75]
}

df = pd.DataFrame(data)

print(df)

    Name  Marks
0    Ali   80.0
1   Sara    NaN
2  Ahmed   75.0

Check Missing Values

In [ ]:
print(df.isnull())

    Name  Marks
0  False  False
1  False   True
2  False  False

To count missing values:

In [ ]:
print(df.isnull().sum())

Name     0
Marks    1
dtype: int64

Remove Missing Values

dropna() removes rows containing missing values.

In [ ]:
df = df.dropna()
df

    Name  Marks
0    Ali   80.0
2  Ahmed   75.0

## Fill Missing Values

Instead of deleting them:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [80, None, 75]
}

df = pd.DataFrame(data)

df['Marks'] = df['Marks'].fillna(0)
df

    Name  Marks
0    Ali   80.0
1   Sara    0.0
2  Ahmed   75.0

We can also fill missing marks using average marks:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [80, None, 75]
}

df = pd.DataFrame(data)

df['Marks'] = df['Marks'].fillna(df['Marks'] .mean())
df

    Name  Marks
0    Ali   80.0
1   Sara   77.5
2  Ahmed   75.0

# 15. Handling Duplicate Data

Sometimes the same record appears more than once.

Example:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ali"],
    "Marks": [80, 90, 80]
}

df = pd.DataFrame(data)
df

   Name  Marks
0   Ali     80
1  Sara     90
2   Ali     80

Check duplicates:


The last row is a duplicate.

In [ ]:
print(df.duplicated())

0    False
1    False
2     True
dtype: bool

To count duplicates:

In [ ]:
print(df.duplicated().sum())

1

To remove duplicates:

Duplicate removal is also part of data cleaning.

In [ ]:
df = df.drop_duplicates()
df

   Name  Marks
0   Ali     80
1  Sara     90

# 16. Sorting Data

`sort_values()` arranges data in a particular order.

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [70, 95, 80]
}

df = pd.DataFrame(data)
df

    Name  Marks
0    Ali     70
1   Sara     95
2  Ahmed     80

Sort from lowest to highest:

In [ ]:
print(df.sort_values("Marks"))

    Name  Marks
0    Ali     70
2  Ahmed     80
1   Sara     95

To sort from highest to lowest:

In [ ]:
print(df.sort_values("Marks",ascending=False))

    Name  Marks
1   Sara     95
2  Ahmed     80
0    Ali     70

So:

```
ascending=True  → Smallest to Largest

ascending=False → Largest to Smallest
```

17. Aggregation and GroupBy



Aggregation functions give us summary values.



These functions help us summarize numerical data.


Suppose:

In [ ]:
marks = df['Marks']

Sum

In [ ]:
print(f"Sum : {marks.sum()}")

Sum : 245

Average

In [ ]:
print(f"Average : {marks.mean()}")

Average : 81.66666666666667

Maximum

In [ ]:
print(f"Maximum : {marks.max()}")

Maximum : 95

Minimum

In [ ]:
print(f"Minimum: {marks.min()}")

Minimum: 70

Count

In [ ]:
print(f"Count : {marks.count()}")

Count : 3

## groupby()


groupby() is very important in Data Analysis.



`groupby()` allows us to analyze data according to categories.

Example:

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "Course": ["AI", "Web", "AI", "Web"],
    "Marks": [80, 90, 70, 85]
}

df = pd.DataFrame(data)
df

     Name Course  Marks
0     Ali     AI     80
1    Sara    Web     90
2   Ahmed     AI     70
3  Ayesha    Web     85

Find average marks for each course:

In [ ]:
result = df.groupby("Course")["Marks"].mean()
print(result)

Course
AI     75.0
Web    87.5
Name: Marks, dtype: float64

It works like:

```
AI Students
    ↓
80, 70
    ↓
Average = 75

Web Students
    ↓
90, 85
    ↓
Average = 87.5
```

# 18. Combining DataFrames

Sometimes our data exists in multiple DataFrames.

Pandas allows us to combine them.

## concat()


concat() is useful when we want to join similar datasets vertically.




Suppose:

In [ ]:
df1 =pd.DataFrame({
    "Name" : ["Ali","Sara"],
    "Marks": [80, 90]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Ayesha"],
    "Marks": [75, 85]
    })

Combine them:

In [ ]:

final_df = pd.concat([df1,df2], ignore_index=True)

print(final_df)

     Name  Marks
0     Ali     80
1    Sara     90
2   Ahmed     75
3  Ayesha     85

## merge()

`merge()` combines DataFrames using a common column.

Example:

In [ ]:
students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})

marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [80, 90, 75]
})

Merge using ID:

In [ ]:
final_df = pd.merge(students,marks ,on = 'ID')
print(final_df)

   ID   Name  Marks
0   1    Ali     80
1   2   Sara     90
2   3  Ahmed     75

The common column is:

```
ID
```

So:

```
Students Data
      +
Marks Data
      ↓
Common ID
      ↓
Final DataFrame
```

# Class Practice: Student Performance Analyzer

Now we will use different Pandas concepts in one small program.

## Problem

We have information about different students.

We want to find:

- Average marks
- Highest marks
- Lowest marks
- Passed students
- Failed students
- Course-wise average
- Add a Result column

In [ ]:
data = {
    "Name" : ["Ali","Sara","Ahmed","Ayesha","Zain"],
    "Course" : ["AI", "Web", "AI","Web","AI"],
    "Marks" : [45,90, 75,85, 40]
}

df = pd.DataFrame(data)

print("Student Data:")
print(df)

print(f"\nAverage Marks : {df['Marks'].mean()}")
print(f"Highest Marks : {df['Marks'].max()}")
print(f"Lowest Marks : {df['Marks'].min()}")


passed = df[df['Marks'] >=50]
failed = df[df['Marks'] <50]


print(f"\nPassed students : {passed}")
print(f"Failed students : {failed}")

df["Result"] = df['Marks'].apply(lambda marks : "Pass" if marks >= 50 else "Fail")



print("\nFinal Data:")
print(df)


course_average = df.groupby("Course")["Marks"].mean()
print(f"\nCourse Wise Average : {course_average}")

Student Data:
     Name Course  Marks
0     Ali     AI     45
1    Sara    Web     90
2   Ahmed     AI     75
3  Ayesha    Web     85
4    Zain     AI     40

Average Marks : 67.0
Highest Marks : 90
Lowest Marks : 40

Passed students :      Name Course  Marks
1    Sara    Web     90
2   Ahmed     AI     75
3  Ayesha    Web     85
Failed students :    Name Course  Marks
0   Ali     AI     45
4  Zain     AI     40

Final Data:
     Name Course  Marks Result
0     Ali     AI     45   Fail
1    Sara    Web     90   Pass
2   Ahmed     AI     75   Pass
3  Ayesha    Web     85   Pass
4    Zain     AI     40   Fail

Course Wise Average : Course
AI     53.333333
Web    87.500000
Name: Marks, dtype: float64

# Student Practice Tasks

## Task 1

Create this student DataFrame:

```
Name     Marks
Ali       70
Sara      85
Ahmed     60
Ayesha    95
Zain      45
Find:

- Average marks
- Maximum marks
- Minimum marks
- Total students

In [ ]:
data = {
    "Name" : ["Ali","Sara","Ahmed","Ayesha","Zain"],
    "Course" : ["AI", "Web", "AI","Web","AI"],
    "Marks" : [45,90, 75,85, 40]
}

df = pd.DataFrame(data)

print("Student Data:")
print(df)

print(f"\nAverage Marks : {df['Marks'].mean()}")
print(f"Maximun Marks : {df['Marks'].max()}")
print(f"Minimum Marks : {df['Marks'].min()}")

print(f"\nTotal Students : {len(df['Name'])}")

Student Data:
     Name Course  Marks
0     Ali     AI     45
1    Sara    Web     90
2   Ahmed     AI     75
3  Ayesha    Web     85
4    Zain     AI     40

Average Marks : 67.0
Maximun Marks : 90
Minimum Marks : 40

Total Students : 5

## Task 2

Using the same DataFrame:

Display only students whose marks are greater than or equal to `50`.

Then display students whose marks are less than `50`.

In [ ]:
data = {
    "Name" : ["Ali","Sara","Ahmed","Ayesha","Zain"],
    "Course" : ["AI", "Web", "AI","Web","AI"],
    "Marks" : [45,90, 75,85, 40]
}

df = pd.DataFrame(data)

print("Student Data:")
print(df)

passed = df[df['Marks'] >= 50]
failed = df[df['Marks'] <50]

print(f"\nPassed Students : {passed}")
print(f"\nFailed Students : {failed}")

Student Data:
     Name Course  Marks
0     Ali     AI     45
1    Sara    Web     90
2   Ahmed     AI     75
3  Ayesha    Web     85
4    Zain     AI     40

Passed Students :      Name Course  Marks
1    Sara    Web     90
2   Ahmed     AI     75
3  Ayesha    Web     85

Failed Students :    Name Course  Marks
0   Ali     AI     45
4  Zain     AI     40

## Task 3

Add a new column:

```
City
```

Add different cities for each student.

Then display only students from:

```
Karachi
```

In [ ]:
data = {
    "Name" : ["Ali","Sara","Ahmed","Ayesha","Zain"],
    "Course" : ["AI", "Web", "AI","Web","AI"],
    "Marks" : [45,90, 75,85, 40]
}

df = pd.DataFrame(data)

print("Student Data:")
print(df)

df['City'] = ['Karachi','Lahore','Rawalpindi','Multan','Islamabad']
print(df['Name'] =="karachi")

Student Data:
     Name Course  Marks
0     Ali     AI     45
1    Sara    Web     90
2   Ahmed     AI     75
3  Ayesha    Web     85
4    Zain     AI     40
0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

## Task 4

Create a DataFrame containing:

```
Name
Course
Marks
```

Use these courses:

```
AI
Web
AI
Web
AI
Find the average marks of each course using groupby().

In [7]:
data = {
    "Name" : ["Ali","Sara","Ahmed","Ayesha","Zain"],
    "Course" : ["AI", "Web", "AI","Web","AI"],
    "Marks" : [45,90, 75,85, 40]
}

df = pd.DataFrame(data)

print(f"\nStudent Data : {df}")

average_marks = df.groupby("Course")["Marks"].mean()
print(f"\nAverage Marks of Each Course : {average_marks}\n")

Student Data :      Name Course  Marks
0     Ali     AI     45
1    Sara    Web     90
2   Ahmed     AI     75
3  Ayesha    Web     85
4    Zain     AI     40

Average Marks of Each Course : Course
AI     53.333333
Web    87.500000
Name: Marks, dtype: float64

## Task 5

Create a DataFrame containing some missing marks.

For example:

```
Ali       80
Sara      NaN
Ahmed     70
Ayesha    NaN
Zain      90
```

Find:

- Number of missing values
- Fill missing values with average marks
- Display the cleaned DataFrame

In [11]:
dataset = {
    'Name' : ['Ali','Sara','Ahmed','Ayesha','Zain'],
    'Marks' : [80, None, 70, None, 90]
}
df = pd.DataFrame(dataset)
print(f"Student Data :\n{df}")

print(f"\nNumber Of Missing Values :\n{df.isnull().sum()}")

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

# Display cleaned DataFrame
print(f"\nStudent Data (Cleaned) :\n{df}")

Student Data :
     Name  Marks
0     Ali   80.0
1    Sara    NaN
2   Ahmed   70.0
3  Ayesha    NaN
4    Zain   90.0

Number Of Missing Values :
Name     0
Marks    2
dtype: int64

Student Data (Cleaned) :
     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmed   70.0
3  Ayesha   80.0
4    Zain   90.0